package dhu.cst.humanresource.dao;

import dhu.cst.humanresource.entity.Wage;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.math.BigDecimal;
import java.util.List;
@Mapper
public interface WageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated
     */
    int insert(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated
     */
    Wage selectByPrimaryKey(Integer id);

    @Update("update wage set bonus=#{money} where id=#{id}")
    void updatebonus(@Param("id") Integer id, @Param("money") BigDecimal num);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated
     */
    @Delete("delete from wage where id=#{id}")
    void deletewage(@Param("id") Integer id);

    @Update("update wage set basicwage=#{basicwage} where id=#{id}")
    void updatebasicwage(@Param("id")Integer id, @Param("basicwage") BigDecimal num);
    @Update("update wage set wage=#{wage} where id=#{id}")
    void updatewage(@Param("id")Integer id, @Param("wage") BigDecimal num);
    List<Wage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wage record);
}