package dhu.cst.humanresource.entity;

import java.io.Serializable;
import java.util.Date;

public class Attendance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.arrivetime
     *
     * @mbg.generated
     */
    private Date arrivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.leavetime
     *
     * @mbg.generated
     */
    private Date leavetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.specialcase
     *
     * @mbg.generated
     */
    private String specialcase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.workontime
     *
     * @mbg.generated
     */
    private Date workontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.workofftime
     *
     * @mbg.generated
     */
    private Date workofftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.condition
     *
     * @mbg.generated
     */
    private String condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.rid
     *
     * @return the value of attendance.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.rid
     *
     * @param rid the value for attendance.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.arrivetime
     *
     * @return the value of attendance.arrivetime
     *
     * @mbg.generated
     */
    public Date getArrivetime() {
        return arrivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.arrivetime
     *
     * @param arrivetime the value for attendance.arrivetime
     *
     * @mbg.generated
     */
    public void setArrivetime(Date arrivetime) {
        this.arrivetime = arrivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.leavetime
     *
     * @return the value of attendance.leavetime
     *
     * @mbg.generated
     */
    public Date getLeavetime() {
        return leavetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.leavetime
     *
     * @param leavetime the value for attendance.leavetime
     *
     * @mbg.generated
     */
    public void setLeavetime(Date leavetime) {
        this.leavetime = leavetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.note
     *
     * @return the value of attendance.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.note
     *
     * @param note the value for attendance.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.specialcase
     *
     * @return the value of attendance.specialcase
     *
     * @mbg.generated
     */
    public String getSpecialcase() {
        return specialcase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.specialcase
     *
     * @param specialcase the value for attendance.specialcase
     *
     * @mbg.generated
     */
    public void setSpecialcase(String specialcase) {
        this.specialcase = specialcase == null ? null : specialcase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.workontime
     *
     * @return the value of attendance.workontime
     *
     * @mbg.generated
     */
    public Date getWorkontime() {
        return workontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.workontime
     *
     * @param workontime the value for attendance.workontime
     *
     * @mbg.generated
     */
    public void setWorkontime(Date workontime) {
        this.workontime = workontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.workofftime
     *
     * @return the value of attendance.workofftime
     *
     * @mbg.generated
     */
    public Date getWorkofftime() {
        return workofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.workofftime
     *
     * @param workofftime the value for attendance.workofftime
     *
     * @mbg.generated
     */
    public void setWorkofftime(Date workofftime) {
        this.workofftime = workofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.condition
     *
     * @return the value of attendance.condition
     *
     * @mbg.generated
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.condition
     *
     * @param condition the value for attendance.condition
     *
     * @mbg.generated
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", id=").append(id);
        sb.append(", arrivetime=").append(arrivetime);
        sb.append(", leavetime=").append(leavetime);
        sb.append(", note=").append(note);
        sb.append(", specialcase=").append(specialcase);
        sb.append(", workontime=").append(workontime);
        sb.append(", workofftime=").append(workofftime);
        sb.append(", condition=").append(condition);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}