package dhu.cst.humanresource.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class History implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.entrytime
     *
     * @mbg.generated
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.skill
     *
     * @mbg.generated
     */
    private String skill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.salary
     *
     * @mbg.generated
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.departmentname
     *
     * @mbg.generated
     */
    private Integer departmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.authority
     *
     * @mbg.generated
     */
    private Integer authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.rank
     *
     * @mbg.generated
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.resignation
     *
     * @mbg.generated
     */
    private Date resignation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.experience
     *
     * @mbg.generated
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.name
     *
     * @return the value of history.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.name
     *
     * @param name the value for history.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.entrytime
     *
     * @return the value of history.entrytime
     *
     * @mbg.generated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.entrytime
     *
     * @param entrytime the value for history.entrytime
     *
     * @mbg.generated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.phone
     *
     * @return the value of history.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.phone
     *
     * @param phone the value for history.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.email
     *
     * @return the value of history.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.email
     *
     * @param email the value for history.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.sex
     *
     * @return the value of history.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.sex
     *
     * @param sex the value for history.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.skill
     *
     * @return the value of history.skill
     *
     * @mbg.generated
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.skill
     *
     * @param skill the value for history.skill
     *
     * @mbg.generated
     */
    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.salary
     *
     * @return the value of history.salary
     *
     * @mbg.generated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.salary
     *
     * @param salary the value for history.salary
     *
     * @mbg.generated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.departmentname
     *
     * @return the value of history.departmentname
     *
     * @mbg.generated
     */
    public Integer getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.departmentname
     *
     * @param departmentname the value for history.departmentname
     *
     * @mbg.generated
     */
    public void setDepartmentname(Integer departmentname) {
        this.departmentname = departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.authority
     *
     * @return the value of history.authority
     *
     * @mbg.generated
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.authority
     *
     * @param authority the value for history.authority
     *
     * @mbg.generated
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.rank
     *
     * @return the value of history.rank
     *
     * @mbg.generated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.rank
     *
     * @param rank the value for history.rank
     *
     * @mbg.generated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.resignation
     *
     * @return the value of history.resignation
     *
     * @mbg.generated
     */
    public Date getResignation() {
        return resignation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.resignation
     *
     * @param resignation the value for history.resignation
     *
     * @mbg.generated
     */
    public void setResignation(Date resignation) {
        this.resignation = resignation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.experience
     *
     * @return the value of history.experience
     *
     * @mbg.generated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.experience
     *
     * @param experience the value for history.experience
     *
     * @mbg.generated
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", entrytime=").append(entrytime);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", sex=").append(sex);
        sb.append(", skill=").append(skill);
        sb.append(", salary=").append(salary);
        sb.append(", departmentname=").append(departmentname);
        sb.append(", authority=").append(authority);
        sb.append(", rank=").append(rank);
        sb.append(", resignation=").append(resignation);
        sb.append(", experience=").append(experience);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}